framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    delay: 3000
                    # Multiplicateur pour augmenter le délai à chaque tentative
                    multiplier: 2
                    # Délai maximum en ms (ex: 1 heure)
                    max_delay: 3600000
                    # Nombre maximum de retries
                    max_retries: 3
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\ConvertAudioMessage: async
            App\Message\AudioSplitMessage: async
            App\Message\AudioToTextMessage: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
