twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'tailwind_2_layout.html.twig'
    globals:
        mercure_public_url: '%env(MERCURE_PUBLIC_URL)%'

when@test:
    twig:
        strict_variables: true
